---
title: "Análise Exploratória de Dados"
author: "Matheus Assis e Oliveira"
date: "2023-10-10"
output:
  pdf_document: default
  html_document: default
---

```{r carregar os pacotes, echo = TRUE}
library(corrplot)
library(RColorBrewer)
library(ggplot2)
library(ggpubr)
```

matriz de correlação

```{r matriz de correlações, echo=TRUE}
# análise exploratória

# Montar uma matriz de correlação básica de cada indicador
#criar data frame que remova as linhas com nulos.

cc = complete.cases(key.ind)
key.corr = key.ind[cc,]

#remover não numérico
key.corr$Territorialidades <- NULL
key.corr$ano <- NULL

### Matriz de corelação com Corrplot

Matrix <-cor(key.corr)
corrplot(Matrix, type="upper", order="hclust", method="pie",
         col=brewer.pal(n=8, name="RdYlBu"))
# gini, theil e população tem relação fraca com IDHM. mas irei manter para análise
```



```{r montar data frame para regressões, echo=TRUE}
# Montar um df para (IDHM ~ renda per capita, sub. ind. ecolaridade, sub. nd. frequencia escolar e esperança de vida.)
predict.IDHM <- renda_per_capita
predict.IDHM <- join(predict.IDHM, sub_esco_pop, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, sub_freq_esco, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, esperança_de_vida, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, porcent_pobres, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, população_total, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, mortalidade_infantil, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, media_anos_de_estudo, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, indice_gini, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, ind_theil_L, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, analfabetismo_25_anos_mais_idade, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, analfabetismo_18_anos_mais_idade, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, analfabetismo_15_anos_mais_idade, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM <- join(predict.IDHM, IDHM, by = c("ano" = "ano", "Territorialidades" = "Territorialidades"))
predict.IDHM$Territorialidades <- NULL 
cc = complete.cases(predict.IDHM)
predict.IDHM = predict.IDHM[cc,]
str(predict.IDHM)
```


```{r scatterplot, echo = TRUE}
### Plotar a correlação como scatterplot matrix.
plot(predict.IDHM, pch=1 , cex=.2, col=rgb(0,0,0,0.4) , main = "Matrix Scatterplot of Variables with Strong Correlation to HDI")

```

 relações lineares com potenciais relações diretas entre os indicadores

````{r scatterplot com linha de regressão e os resultados, echo = TRUE}
# Criar um scatterplot com linha de regressão para IDHM e renda per capita
ggscatter(predict.IDHM, x = "renda_per_capita", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ renda_per_capita, data=predict.IDHM))

# Criar um scatterplot com linha de regressão para IDHM demais indicadores
ggscatter(predict.IDHM, x = "sub_esco_pop", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ sub_esco_pop, data=predict.IDHM))


ggscatter(predict.IDHM, x = "sub_freq_esco", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ sub_freq_esco, data=predict.IDHM))


ggscatter(predict.IDHM, x = "esperança_de_vida", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ esperança_de_vida, data=predict.IDHM))

ggscatter(predict.IDHM, x = "porcent_pobres", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ porcent_pobres, data=predict.IDHM))


ggscatter(predict.IDHM, x = "população_total", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ população_total, data=predict.IDHM))


ggscatter(predict.IDHM, x = "mortalidade_infantil", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ mortalidade_infantil, data=predict.IDHM))



ggscatter(predict.IDHM, x = "media_anos_de_estudo", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ media_anos_de_estudo, data=predict.IDHM))



ggscatter(predict.IDHM, x = "indice_gini", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ indice_gini, data=predict.IDHM))



ggscatter(predict.IDHM, x = "ind_theil_L", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ ind_theil_L, data=predict.IDHM))


ggscatter(predict.IDHM, x = "analfabetismo_25_anos_mais_idade", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ analfabetismo_25_anos_mais_idade, data=predict.IDHM))


ggscatter(predict.IDHM, x = "analfabetismo_18_anos_mais_idade", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ analfabetismo_18_anos_mais_idade, data=predict.IDHM))


ggscatter(predict.IDHM, x = "analfabetismo_15_anos_mais_idade", y = "IDHM", color=rgb(1,.8,0,.3),pch=1,
          add = "reg.line", add.params = list(color=rgb(0,.4,.4,  1), fill = "light gray"),
          conf.int = TRUE)
# Printar estatística F para ver a significacia da regressão
summary(lm(IDHM ~ analfabetismo_15_anos_mais_idade, data=predict.IDHM))

````
avaliar os decils para conferir existencia de outliers

````{r decils, echo = TRUE }
print(paste0("renda_per_capita"))
quantile(predict.IDHM$renda_per_capita, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$renda_per_capita)
print(paste0("sub_esco_pop"))
quantile(predict.IDHM$sub_esco_pop, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$sub_esco_pop)
print(paste0("sub_freq_esco"))
quantile(predict.IDHM$sub_freq_esco, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$sub_freq_esco)
print(paste0("esperança_de_vida"))
quantile(predict.IDHM$esperança_de_vida, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$esperança_de_vida)
print(paste0("porcent_pobres"))
quantile(predict.IDHM$porcent_pobres, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$porcent_pobres)
print(paste0("população_total"))
quantile(predict.IDHM$população_total, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$população_total)
print(paste0("mortalidade_infantil"))
quantile(predict.IDHM$mortalidade_infantil, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$mortalidade_infantil)
print(paste0("media_anos_de_estudo"))
quantile(predict.IDHM$media_anos_de_estudo, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$media_anos_de_estudo)
print(paste0("indice_gini"))
quantile(predict.IDHM$indice_gini, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$indice_gini)
print(paste0("ind_theil_L"))
quantile(predict.IDHM$ind_theil_L, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$ind_theil_L)
print(paste0("analfabetismo_25_anos_mais_idade"))
quantile(predict.IDHM$analfabetismo_25_anos_mais_idade, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$analfabetismo_25_anos_mais_idade)
print(paste0("analfabetismo_18_anos_mais_idade"))
quantile(predict.IDHM$analfabetismo_18_anos_mais_idade, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$analfabetismo_18_anos_mais_idade)
print(paste0("analfabetismo_15_anos_mais_idade"))
quantile(predict.IDHM$analfabetismo_15_anos_mais_idade, probs = seq(.1, 1, by = .1))
sort(predict.IDHM$analfabetismo_15_anos_mais_idade)
````



